repo_url: https://github.com/kulpig9799/notes-site
repo_name: kulpig9799/notes-site
edit_uri: edit/main/docs/

site_name: Ghi chú của tôi
site_description: Wiki học tập cá nhân (DBA, SQL, Linux, Tối ưu SQL, Python, Data Engineer)
site_url: ""
theme:
  name: material
  language: vi
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.superfences

