name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]      # cứ push vào main là tự build
  workflow_dispatch:        # cho phép bấm "Run workflow" thủ công

permissions:
  contents: write           # cần quyền ghi để push lên gh-pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0     # giữ lịch sử git đầy đủ cho gh-deploy
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions
          pip install -r requirements.txt
      - name: Build & Deploy to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force --clean --verbose
